#!/usr/bin/env sh
rm -rf /tmp/vfilter/*
rm -rf vfilter.db
rm -rf vpn.csv
./getnewfile 138.201.173.225:58292 
./solv.py
#import result ovpn to system
#for file in $(ls -1);do nmcli connection import type openvpn file $file;done